version: '3.7'

services:
  osint-grafana:
    build: './config/grafana'
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  osint-prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
  osint-db:
    image: 'postgres:14-alpine'
    container_name: osint-db
    ports:
      - 5450:5432
    environment:
      POSTGRES_USER: osint_admin
      POSTGRES_PASSWORD: osint_admin
      POSTGRES_DB: osint_db
    volumes:
      - ./db/imports:/docker-entrypoint-initdb.d
      - ./db/db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U osint_admin -d osint_db
      interval: 1s
      timeout: 30s
      retries: 10
    networks:
      monitoring:
        aliases:
          - osint-db

#  osint-flyway:
#    image: flyway/flyway:9.9.0
#    command: -url='jdbc:postgresql://osint-db:5432/osint_db' -schemas=osint_web_v2 -user=osint_admin -password=osint_admin -connectRetries=60 migrate
#    volumes:
#      - ./flyway/sql:/flyway/sql
#    depends_on:
#      tutor-db:
#        condition: service_healthy

networks:
  monitoring: