server:
  port: 8190
  servlet:
    context-path: /OSINT
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
spring:
  application:
    name: Osint_db_service

  datasource:
    url: jdbc:postgresql://localhost:5431/osint_db
    username: osint_admin
    password: osint_admin
    driverClassName: org.postgresql.Driver
    dbcp2:
      test-on-borrow: true
      validation-query: SELECT 1;
      validation-query-timeout: 30000
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
    hikari:
      max-lifetime: 60000
      maximum-pool-size: 10
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

logging:
  level:
    root: info
    ru.get: debug
    org.springframework.web: info
    org.hibernate: error
  file:
    name: ./Logs/isBackend.log
  charset:
    console: UTF-8
    file: UTF-8